version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
          no_output_timeout: 50m
          command: |
           apt-get -y update && apt-get -y upgrade && DEBIAN_FRONTEND=noninteractive apt-get -y install bc build-essential python ccache kernel-package libncurses5-dev bzip2 zip gcc clang libc6 curl libstdc++6 git wget gcc-multilib g++-multilib libssl-dev zstd openjdk-11-jdk openjdk-11-jre gcc-10 g++-10
           git clone --depth=1 -b release https://github.com/silont-project/kernel_realme_RMX1971.git kernal
           cd kernal
           git clone --depth=1 https://github.com/nanananonono/scripts -b silont kscripts
           source ./kscripts/envsetup.sh
           ./kscripts/circle.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
